version: '3'

services:
  yasm_client:
    build:
      context: client
      dockerfile: Dockerfile
    container_name: yasm_client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/client
      - /client/node_modules
    networks:
      - yasm_net
    depends_on:
      - yasm_server

  yasm_server:
    build:
      context: server
      dockerfile: Dockerfile
    container_name: yasm_server
    env_file:
      - server.env
    ports:
      - '5000:5000'
    volumes:
      - ./server:/server
      - /server/node_modules
    networks:
      - yasm_net
    depends_on:
      - yasm_postgres

  yasm_postgres:
    image: postgres
    container_name: yasm_postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - postgres.env
    volumes:
      - yasm_postgres:/var/lib/postgresql/data
    networks:
      - yasm_net

networks:
  yasm_net:
    name: yasm_net

volumes:
  yasm_postgres:
    driver: local
